server:
  http_listen_port: 3100

positions:
  filename: /tmp/positions.yaml

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        directory: /loki/chunks
      storage_config:
        boltdb_shipper:
          active_index_directory: /loki/index
          shared_store: filesystem
          cache_location: /loki/cache

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
